### PR TITLE
fix: also set ssrAppId for first Vue app when ssrAttribute exists

### LINKED ISSUE #404: vue-meta duplicating tags on SSR hydration
Specifically it looks like this line:

https://github.com/nuxt/vue-meta/blob/f1511ac566588adef7558dd02219688d860d6d35/src/shared/mixin.js#L82

checks to see if the app is performing SSR hydration

However, by the time it gets here, Vue's already removed the `data-server-rendered` attribute from the root element, and so it recreates all the tags.

I haven't looked into this in-depth, but could you just set all the tags to include `data-vue-meta="1"` during SSR instead of `data-vue-meta="ssr"` and skip this check?

Using vue@2.6.10

### LINKED ISSUE #562: Duplicate html "lang" attribute on page redirect from SSR
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://gitlab.com/njam/repro-nuxt-html-lang](https://gitlab.com/njam/repro-nuxt-html-lang)

### Steps to reproduce

1: Clone the repro repo:
```
git clone https://gitlab.com/njam/repro-nuxt-html-lang
cd repro-nuxt-html-lang
```
(relevant commit: https://gitlab.com/njam/repro-nuxt-html-lang/-/commit/be48fd82f0fdfd8197dbf7870a4cb9d74778a09f)

2: Build the static files, and serve them
```
yarn install
yarn run generate
npx serve ./dist
```

3: Open the page in the browser: http://localhost:5000

### What is expected ?

The browser redirects to "/foo", and the html-tag has the attribute `lang="de"`

### What is actually happening?

The browser redirects to "/foo", and the html-tag has the attribute `lang="de de"`

Open the browser's dev tools to inspec the "lang" attribute:  

### Additional comments?

Maybe vue-meta cannot correctly detect that the previous "lang"-value is coming from a server-rendered file when redirecting?

This vue-meta ticket might be related: https://github.com/nuxt/vue-meta/issues/404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10664">#c10664</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by pimlie**
This should resolve #404 and resolve #562 

@kevinmarrec Would this fix be an issue with Vuetify? I know previously we had issues with that because they start new Vueapp's for modals etc. But I would guess that if you use Vuetify with SSR the Vue app that uses Vuetify will be initiated first?

I feel this fix is a bit hacky, but I dont think there is a proper way that vue-meta can currently pass the appId from ssr to the client without introducing a breaking change. This fix should handle like 99+% of the normal use-cases (if Vuetify plays along).

(The reverts are just because I first pushed on master, but then decided it was better to do a PR first)

### CODE REVIEW

File: src/shared/mixin.js [hunk 1]
```diff
@@ -39,6 +34,22 @@ export default function createMixin (Vue, options) {
...
+      if (this === $root) {
+        $root.$once('hook:beforeMount', function () {
+          wasServerRendered = this.$el && this.$el.nodeType === 1 && this.$el.hasAttribute('data-server-rendered')
+
+          // In most cases when you have a SSR app it will be the first app thats gonna be
+          // initiated, if we cant detect the data-server-rendered attribute from Vue but we
+          // do see our own ssrAttribute then _assume_ the Vue app with appId 1 is the ssr app
+          // attempted fix for #404 & #562, but we rly need to refactor how we pass appIds from
+          // ssr to the client
+          if (!wasServerRendered && $root[rootConfigKey] && $root[rootConfigKey].appId === 1) {
```
Comment (pimlie) [inline src/shared/mixin.js:46]: This if is the possible hacky part

**Comment by njam** [comment]
I can't say much about the correctness of the detection of `wasServerRendered`.

But I can confirm that this fixes https://github.com/nuxt/vue-meta/issues/562 (Nuxt SSR).

File: src/shared/mixin.js (hunk 1 above)
Comment (Atinux) [reply src/shared/mixin.js:46]: `this.$el.hasAttribute('data-server-rendered')` will work only for Vue 2 anyway
