### PR TITLE
fix: afterNavigation

### LINKED ISSUE #475: bug afterNavigation
Setup two pages with Nuxt.js:

```vue
<!-- pages/page1.vue -->
<template>
  <div>
    <h1 class="title">Page 1</h1>

    <div class="links">
      <nuxt-link to="page1">Page 1</nuxt-link>
      <nuxt-link to="page2">Page 2</nuxt-link>
    </div>
  </div>
</template>

<script>
export default {
  head() {
    return {
      title: 'Page 1',
      afterNavigation(metaInfo) {
        console.log(metaInfo.title) // Page 2
      }
    };
  },
}
</script>
```

```vue
<!-- pages/page2.vue -->
<template>
  <div>
    <h1 class="title">Page 2</h1>

    <div class="links">
      <nuxt-link to="page1">Page 1</nuxt-link>
      <nuxt-link to="page2">Page 2</nuxt-link>
    </div>
  </div>
</template>


<script>
export default {
  head() {
    return {
      title: 'Page 2',
      afterNavigation(metaInfo) {
        console.log(metaInfo.title) // Page 1
      }
    };
  },
}
</script>
```

**Expected behavior:**
Page 1 will track "Page 1" as title
Page 2 will track "Page 2" as title

**Actual behavior:**
Page 1 & Page 2 tracks title correctly during initial load
Page 2 tracks "Page 1" when changing route from Page 1 -> Page 2
Page 1 tracks "Page 2" when changing route from Page 2 -> Page 1

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Resolve #475 

Need disable `features.transitions: false`

### CODE REVIEW

File: src/shared/nav-guards.js [hunk 1]
```diff
@@ -19,10 +19,12 @@ export function addNavGuards (rootVm) {
   })
 
   router.afterEach(() => {
-    const { metaInfo } = resume(rootVm)
+    rootVm.$nextTick(function () {
```
Comment (pimlie) [inline src/shared/nav-guards.js]: Couldnt this be an arrow function?

Comment (ricardogobbosouza) [reply src/shared/nav-guards.js]: yeap

**Comment by pimlie** [comment]
@ricardogobbosouza Thanks btw :)
